### PR TITLE
Edit default pronouns to add consistency

### PR DESCRIPTION
**Pull request by ineffyble**
If the first two are "He/Him" and "She/Her", the third should be "They/Them" to follow the pattern of Subjective/Objective.

### CODE REVIEW

**Comment by ineffyble** [comment]
I am guessing to fix this on our installation we just need to edit the option group via the GUI?

**Comment by andrew-cormick-dockery** [comment]
> 
> 
> I am guessing to fix this on our installation we just need to edit the option group via the GUI?

Shouldn't that be in the upgrade section of the code?

**Comment by seamuslee001** [comment]
Possibly an upgrade would work we would also probably want to fix any custom field values already

**Comment by seamuslee001** [comment]
@andrew-cormick-dockery @johntwyman i have also included an upgrade function now and tested that on a dev box and seems to do what i expect @ineffyble are you ok with the upgrade function here?

**Comment by ineffyble** [comment]
LGTM 👍

**Review by johntwyman — APPROVED** [review]

**Review by seamuslee001 — APPROVED** [review]

**Review by anthonyblond — APPROVED** [review]

**Review by johntwyman — APPROVED** [review]

**Pull request merged**
